# Generated by Django 2.0.7 on 2018-08-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300)),
                ('contactnumber', models.TextField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('flavor', models.CharField(max_length=300)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
            ],
        ),
    ]
