# Generated by Django 2.0.7 on 2018-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contactnumber',
            field=models.BigIntegerField(),
        ),
    ]
