# Generated by Django 2.0.7 on 2018-08-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0003_auto_20180804_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='order',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
