# Generated by Django 2.0.7 on 2018-08-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0004_auto_20180805_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image1',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image2',
            field=models.FileField(null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
