# Generated by Django 2.0.7 on 2018-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0005_auto_20180805_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image1',
            field=models.FileField(null=True, upload_to='documents/%Y%m%d/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='image2',
            field=models.FileField(null=True, upload_to='documents/%Y%m%d/'),
        ),
    ]
