# Generated by Django 2.0.7 on 2018-08-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0007_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.IntegerField(choices=[(0, 'Chocolate Chip'), (1, 'Chocolate Fudge'), (2, 'Nutella'), (3, 'Cheese'), (4, 'Strawberry Cheese')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(-1, 'Rejected'), (0, 'Not-Accepted'), (1, 'Accepted'), (2, 'Ready-for-delivery'), (3, 'Completed')], default=0),
        ),
    ]
