# Generated by Django 2.0.7 on 2018-09-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderform', '0009_auto_20180908_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contactnumber',
            field=models.CharField(max_length=300),
        ),
    ]
